server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://108.136.236.166:3306/vinv_customer
    username: vinv
    password: vinv@app
    jpa:
      show-sql: true
  kafka:
    consumer:
#      Read latest or earliest ofset
      auto-offset-reset: latest
      group-id: 1
    bootstrap-servers: 108.136.236.103:9092